# Purpose is to simplify the creation of a new configuration installer.

# Globals
CONFIG_NAME=""
FILENAME=""

read -rp "Please enter the name of the new config (abbrv if necessary): " CONFIG_NAME

# Do some verification that it does not exist on the remote.
mkdir -p ~/"$CONFIG_NAME" || echo "Failed to create new config." # Checks local
cd ~/"$CONFIG_NAME" || echo "Failed to go to new config."

# Create install script
FILENAME="install_${CONFIG_NAME}.sh"
touch "$FILENAME" 
chmod u+x "$FILENAME"

cat << EOF > "$FILENAME"
# This script was auto generated.
# This script will run first.
# Do not change it's name!
EOF

# Create README
touch "README.md"
cat << EOF > "README.md"
<!---
 The directory $CONFIG_NAME and the script $FILENAME were autogenerated.
 Do not change their names!
-->
EOF
