#!/bin/bash/

# 
# Loggin Library
# Provides structured logging with levels, colors, and formatting
#
# Usage: source ./logger.sh
#

[[ "${_LOGGER_LOADED:-}" == "true" ]] && return 0
readonly _LOGGER_LOADED=true

_load_dependencies() {
    source "./libs/ansi_codes.sh"
}
